import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import { Providers } from "@/provider/ChakraProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <title>Cahaya Lead</title>
        <meta name="description" content="Cahaya Lead" />
        <meta property="og:url" content="https://s2lmjsk7-3000.asse.devtunnels.ms" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="Cahaya Lead" />
        <meta property="og:description" content="Technology Partner" />
        <meta property="og:image" content="" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta property="twitter:domain" content="s2lmjsk7-3000.asse.devtunnels.ms" />
        <meta property="twitter:url" content="https://s2lmjsk7-3000.asse.devtunnels.ms" />
        <meta name="twitter:title" content="Cahaya Lead" />
        <meta name="twitter:description" content="Generated by create next app" />
        <meta name="twitter:image" content="" />
      </Head>
      <body className={inter.className}>
        <Providers>
          <Navbar />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  );
}